# Generated by Django 5.2.1 on 2025-05-14 07:56

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.CharField(default=core.utils.generate_id, max_length=255, primary_key=True, serialize=False),
        ),
    ]
