# Generated by Django 5.2.1 on 2025-05-20 02:51

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0004_document_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.CharField(default=core.utils.generate_id, max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('role', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
